package engine.menu;

import engine.Game;
import engine.MenuPanel;
import java.awt.event.ActionEvent;

/**
 *
 * @author Voki
 */
public class Keybindings extends MenuPanel {

    public Keybindings(Game game) {
        super(game);
        initComponents();
        back.addActionListener((ActionEvent e) -> {
            game.setMenu(game.options);
        });
    /*setLayout(null);
        JButton batton = new JButton("ZEBATTHON");

        add(batton);
        batton.setBounds(50, 50, 100, 100);
        batton.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {

                Rectangle dim = batton.getBounds();
                switch (e.getKeyChar()) {
                    case 'w':
                        batton.setBounds(dim.x, dim.y - 10, dim.width, dim.height);
                        break;
                    case 's':
                        batton.setBounds(dim.x, dim.y + 10, dim.width, dim.height);
                        break;
                    case 'a':
                        batton.setBounds(dim.x - 10, dim.y, dim.width, dim.height);
                        break;
                    case 'd':
                        batton.setBounds(dim.x + 10, dim.y, dim.width, dim.height);
                        break;
                        default:
                            System.out.println(e.getKeyChar());
                }
                batton.revalidate();
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();

        back.setText("back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    // End of variables declaration//GEN-END:variables
}
